### ISSUE TITLE
.grist-api-key shouldn't be at ~/

### ISSUE THREAD

**Issue by j2l** [gristlabs/grist-api#8]
mainly because you can't test the npm package on replit, codesandbox, glitch, ...
and also because not all js are run under a user with a ~ folder.

![image](https://user-images.githubusercontent.com/65325/126827405-6e7546f3-b379-4b55-9a05-05a3faa30458.png)

/home/runner is on replit server, pretty sure nobody can reach it :smile: 

Also, since "everyone" user has read access, it should work without it.
It works in postman without any authentication.

**Comment by dsagal** [comment]
There are several ways to provide the key -- via constructor, or environment variable, and via `~/.grist-api-key` as a convenient fallback. I could make the error message mention that.

And you are right that it's a problem that there is no way to run without an API key -- I'll fix that!

**Comment by j2l** [comment]
Fantastic!
Thank you @dsagal
